### ISSUE TITLE
não tem opção de tradução

### ISSUE THREAD

**Issue by Alexmadei** [AdobeDocs/document-cloud-learn.pt-BR#1]

**Comment by Alexmadei** [comment]
>Alguns videos não tem a opçao de tradução do aúdio

**Comment by danilo-miranda** [comment]
Obrigado pelo contato e pelo feedback, @Alexmadei, vamos analisar o caso.

**Comment by KristynaVitekerova** [comment]
Agradecemos novamente pelo seu feedback. A questão está sendo revisada e monitorada em G11N-14009.

**Comment by danilo-miranda** [comment]
O ticket do Jira foi resolvido, e o problema foi corrigido.

**Comment by danilo-miranda** [comment]
O ticket do Jira foi resolvido, e o problema foi corrigido.
